/* An SEO helper package for Meteor.js. 
 * Originally posted as an article here: manuel-schoebel.com/blog/meteor-and-seo
 *
 * Author: Manuel Schoebel 
 * Git: "https://github.com/DerMambo/ms-seo.git"
 * Version: "0.4.1"
 */

// Generated by CoffeeScript 1.9.3
(function() {
  this.SeoCollection = new Mongo.Collection('seo');

}).call(this);
